= Modernize an API Using Anypoint Studio

This walkthrough shows how you can use Anypoint Studio to modernize a SOAP-based web service by fully integrating it to a REST-based Mule application.

== Learn How To Use Anypoint Studio Tools for APIs

This tutorial starts with a SOAP based web service that handles t-shirt orders and order tracking with an hypothetical database and seamlessly walks you through:

. Using API Designer to define a RESTful API to match the SOAP resources you want to update.
. Creating a proxy for your new API project.
. Importing your RAML definition to Anypoint Studio and automatically leverage the flow design to the APIKit component, that automatically handles behavior for each defined resource and error codes.
. In less than four clicks, automatically creating unit tests for each of your flows, taking advantage of the MUnit framework.
. Using Anypoint Studio's connectors to integrate your SOAP service to your Mule application.
. Syncing your work with API Designer using Studio's API Sync view.
. Updating your existing test to validate your now integrated Mule application with the legacy SOAP web service.

Start now by link:/anypoint-platform-for-apis/create-an-api[designing and creating your API definition] with Anypoint Platform's API Designer.
