= APIKit
:keywords: api, apikit, raml

APIkit is an open-source project that simplifies the development of RAML-based APIs with Mule flows. When you use an existing RAML that declares a baseURI to create a Mule project, the APIkit Router appears in your flow. Some tasks that the APIkit Router performs are:

* Routes messages
* Validates payloads, headers, query-params, uri-params
* Serializes responses

Message routing consists of routing incoming API requests to existing Mule flows and returning outgoing HTTP response codes to exceptions.

APIkit generates a backend flow for each resource/action pairing in your RAML. Backend flows mock responses of the API for testing using the console. APIkit projects includes the same console as the API Designer tool. API and application developers use the console to interact with the API and browse RAML embedded documentation.

== Get Started with APIkit

. Study the link:/anypoint-platform-for-apis/apikit-basic-anatomy[Basic Anatomy of APIkit] to examine the parts that make up the whole.

. Learn by example. Follow the link:/anypoint-platform-for-apis/apikit-tutorial[APIkit Tutorial] to install APIkit, then build, deploy and test a REST API.

. Access link:http://raml.org/[RAML.org] to learn how to build your API interface using link:https://github.com/raml-org/raml-spec[RAML] and its link:http://raml.org/projects.html[intuitive tooling].
